---
title: "06_analysis_2"
format: 
  html:
    embed-resources: true
editor: visual
---

## Loading libraries and functions

```{r}
#| message: false
library(tidyverse)
source("99_proj_func.R")
```

## Loading dataset

```{r}
#| message: false
#| warning: false
data_path = "../data/"
results_path = "../results/"
df <- read_tsv(paste0(data_path, "merged_data.tsv"))
```

## **Combine all side-effect for each drug into a single row**

```{r}
df_drug <- df |>
  group_by(drugbank_id) |>
  summarise(
    common_name = first(common_name),
    drug_groups = first(drug_groups),
    smiles = first(smiles),
    formula = first(formula),
    uniprot_names = first(uniprot_names),
    molecular_weight = first(molecular_weight),
    hbd = first(hbd),
    hba = first(hba),
    clog_p = first(clog_p),
    lipinski = first(lipinski),
    # side effects
    side_effects = str_c(unique(side_effect_PT), collapse = "; "),
    side_effect_burden = n_distinct(side_effect_PT),
    .groups = "drop"
  )
```

## Distributions of Lipinski-related descriptors

```{r}
# Histogram for H-bond donors (HBD) 
df_drug |>
  ggplot(aes(x = hbd,
             y = ..count.. / sum(..count..) * 100)) +
  geom_histogram(binwidth = 1,
                 fill = "steelblue",
                 color = "black") +
  theme_bw() +
  labs(x = "H-bond donors (HBD)",
       y = "Percentage (%)")

ggsave(paste0(results_path,"Analysis2_HBD_count.png"), plot = last_plot(), 
       width = 8, height = 6, dpi = 300)

# Histogram for H-bond acceptors (HBA) 
df_drug |>
  ggplot(aes(x = hba,
             y = ..count.. / sum(..count..) * 100)) +
  geom_histogram(binwidth = 1,
                 fill = "steelblue",
                 color = "black") +
  theme_bw() +
  labs(x = "H-bond acceptors (HBA)",
       y = "Percentage (%)")

ggsave(paste0(results_path,"Analysis2_HBA_count.png"), plot = last_plot(), 
       width = 8, height = 6, dpi = 300)

# Bar plot for Lipinski rule compliance as percentage
df_drug |>
  ggplot(aes(x = lipinski,
             y = ..count.. / sum(..count..) * 100)) +
  geom_bar(fill = "steelblue",
           color = "black") +
  theme_bw() +
  labs(x = "Lipinski rule satisfied",
       y = "Percentage (%)")

ggsave(paste0(results_path,"Analysis2_Lipinski_percent.png"), plot = last_plot(), 
       width = 8, height = 6, dpi = 300)


# Density plot for Molecular Weight (MW)
df_drug |>
  ggplot(aes(x = molecular_weight)) +
  geom_density(fill = "lightgreen",
               alpha = 0.6) +
  theme_bw() +
  labs(x = "Molecular Weight (MW)",
       y = "Density")
ggsave(paste0(results_path,"Analysis2_MW_density.png"), plot = last_plot(), 
       width = 8, height = 6, dpi = 300)

# Density plot for LogP (ClogP)
df_drug |>
  ggplot(aes(x = clog_p)) +
  geom_density(fill = "lightgreen",
               alpha = 0.6) +
  theme_bw() +
  labs(x = "LogP (ClogP)",
       y = "Density")
ggsave(paste0(results_path,"Analysis2_LogP_density.png"), plot = last_plot(), 
       width = 8, height = 6, dpi = 300)
```

## Correlation plots with side-effect burden

```{r}

# HBD vs side-effect burden
df_drug |>
  ggplot(aes(x = hbd,
             y = side_effect_burden)) +
  geom_point(color = "steelblue", alpha = 0.6) +
  theme_bw() +
  labs(x = "H-bond donors (HBD)",
       y = "Number of Side Effects")
ggsave(paste0(results_path,"Analysis2_HBD_SE.png"), plot = last_plot(), 
       width = 8, height = 6, dpi = 300)

# HBA vs side-effect burden
df_drug |>
  ggplot(aes(x = hba,
             y = side_effect_burden)) +
  geom_point(color = "steelblue", alpha = 0.6) +
  theme_bw() +
  labs(x = "H-bond acceptors (HBA)",
       y = "Number of Side Effects")

ggsave(paste0(results_path,"Analysis2_HBA_SE.png"), plot = last_plot(), 
       width = 8, height = 6, dpi = 300)

# Molecular Weight vs side-effect burden
df_drug |>
  ggplot(aes(x = molecular_weight,
             y = side_effect_burden)) +
  geom_point(color = "steelblue", alpha = 0.6) +
  theme_bw() +
  labs(x = "Molecular Weight (MW)",
       y = "Number of Side Effects")
ggsave(paste0(results_path,"Analysis2_MW_SE.png"), plot = last_plot(), 
       width = 8, height = 6, dpi = 300)

# LogP vs side-effect burden
df_drug |>
  ggplot(aes(x = clog_p,
             y = side_effect_burden)) +
  geom_point(color = "steelblue", alpha = 0.6) +
  theme_bw() +
  labs(x = "LogP (ClogP)",
       y = "Number of Side Effects")
ggsave(paste0(results_path,"Analysis2_LogP_SE.png"), plot = last_plot(), 
       width = 8, height = 6, dpi = 300)


# Lipinski rule vs side-effect burden
df_drug |>
  ggplot(aes(x = lipinski,
             y = side_effect_burden)) +
  geom_boxplot(fill = "steelblue", color = "black") +
  theme_bw() +
  labs(x = "Lipinski Rule Satisfied",
       y = "Number of Side Effects")
ggsave(paste0(results_path,"Analysis2_Lipinski_SE.png"), plot = last_plot(), 
       width = 8, height = 6, dpi = 300)
```

## Legality state

```{r}
df_legal <- df_drug |>
  separate_rows(drug_groups, sep = ";") |> 
  mutate(drug_groups = trimws(drug_groups))     

df_counts <- df_legal |>
  group_by(drug_groups, lipinski) |>
  summarise(n_drugs = n_distinct(common_name), .groups = "drop")


ggplot(df_counts,
       aes(x = drug_groups,
           y = n_drugs,
           fill = lipinski)) +
  geom_bar(stat = "identity",
           color = "black",
           position = position_dodge()) +
  labs(x = "Drug Group",
       y = "Number of Unique Drugs",
       fill = "Lipinski Rule") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(paste0(results_path,"Analysis2_Lipinski_Legal.png"), plot = last_plot(), 
       width = 8, height = 6, dpi = 300)

```
